// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ProductFormController from "./product_form_controller"
application.register("product-form", ProductFormController)

import SiteController from "./site_controller"
application.register("site", SiteController)

import GalleryController from "./gallery_controller"
application.register("gallery", GalleryController)

import PrintController from "./print_controller"
application.register("print", PrintController)

import HeroController from "./hero_controller"
application.register("hero", HeroController)
