
version: '3'

volumes:
  bundle:
  stm_industry_db:

services:
  stm_industry_db:
    container_name: stm_industry_db
    image: nouchka/sqlite3:latest
    volumes:
      - stm_industry_db:/root/db
    stdin_open: true
    tty: true

  stm_industry_dev:
    container_name: stm_industry_cont
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ./node_modules:/app/node_modules
    tmpfs: /app/tmp
    depends_on:
      - stm_industry_db
    env_file: .env
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production