class Constant < ActiveRecord::Base
  attr_accessible :job_stoyki_arx, :job_polki_arx, :job_usil_arx, :job_upakovka_arx, :job_ogranich,
                  :job_okr_stoyki_arx, :job_okr_polki_arx, :job_stoyki_sklad, :job_traversi_sklad,
                  :job_polki_sklad, :job_ukosi_sklad, :job_usil_styagnoy, :job_usil_g, :job_okr_usil_sklad,
                  :job_okr_stoyki_sklad, :job_ork_polki_sklad, :job_okr_traversi_sklad, :job_upakovka_sklad,
                  :job_stoyki_pallet, :job_traversi_pallet, :job_okr_travers_pallet, :job_ukosi_pallet,
                  :job_svarka_ks_01, :job_svarka_ks_02, :job_svarka_ks_03, :job_svarka_ks_04,
                  :job_svarka_pt_01, :job_svarka_pt_02, :job_svarka_pt_03, :job_svarka_pt_04,
                  :job_svarka_tp_01, :job_svarka_tp_02, :job_svarka_tp_03, :job_svarka_tp_04,
                  :job_svarka_tp_05, :job_svarka_tp_06, :job_svarka_tp_07, :job_rezka, :job_okr_telegek,
                  :job_gibka_du_20_25,
                  :job_rixtovka_ugolka, :job_upakovka_teleg, :job_rez_dsp_1mp, :job_natsenka,
                  :job_dostavka_1kg, :job_kostven_arx, :job_kostven_sklad, :job_kostven_pallet,
                  :job_kostven_telegi, :job_natsen_diler, :job_procent_udor_svarki_telegki,
                  :mat_list_2_1_055, :mat_list_2_1_07, :mat_list_25_125_07, :mat_list_2_1_1, :mat_list_2_1_2,
                  :mat_list_25_125_2, :mat_list_2_1_25, :mat_list_25_125_25, :mat_stoyki_arx, :mat_pyatki_arx,
                  :mat_stoyki_sklad, :mat_traversa_sklad, :mat_pyatki_sklad, :mat_metizi_sklad, :mat_ukosi_sklad,
                  :mat_zatsep_sklad, :mat_truba_25_25_12, :mat_truba_25_25_15, :mat_shina_30_4, :mat_skoba_styagnogo,
                  :mat_stoyki_pallet, :mat_pyatki_pallet, :mat_metizi_pallet_ram, :mat_metizi_pallet_travers,
                  :mat_zatsep_pallet, :mat_ukosi_pallet, :mat_truba_25_25_2, :mat_truba_du_20_25,
                  :mat_plastini_teleg, :mat_metizi_teleg, :mat_ugolok_20_20_3, :mat_dsp_laminat, :mat_dsp_shlif,
                  :mat_100x60x100x15,:mat_setka_50_50_3,
                  :wei_truba_25_25_2, :wei_setka_50_50_3,
                  :wei_list_2_1_055, :wei_list_2_1_07, :wei_list_25_125_07, :wei_list_2_1_1, :wei_list_2_1_2,
                  :wei_list_25_125_2, :wei_list_2_1_25, :wei_list_25_125_25, :wei_stoyki_arx,
                  :wei_pyatki_arx, :wei_stoyki_sklad, :wei_traversa_sklad, :wei_pyatki_sklad,
                  :wei_metizi_sklad, :wei_ukosi_sklad, :wei_zatsep_sklad, :wei_truba_25_25_12,
                  :wei_truba_25_25_15, :wei_shina_30_4, :wei_skoba_styagnogo, :wei_stoyki_pallet,
                  :wei_pyatki_pallet, :wei_metizi_pallet_ram, :wei_metizi_pallet_travers,
                  :wei_zatsep_pallet, :wei_ukosi_pallet, :wei_truba_du_20_25, :wei_plastini_teleg,
                  :wei_metizi_teleg, :wei_ugolok_20_20_3, :wei_dsp_laminat, :wei_dsp_shlif, :wei_100x60x100x15,:email_to_send,
                  :on_off_calc_stillage, :on_off_calc_stillage_warehouse, :on_off_calc_stillage_pallet, :on_off_calc_TP01, :on_off_calc_TP02,
                  :on_off_calc_TP03, :on_off_calc_TP04, :on_off_calc_TP05,:on_off_calc_TP06, :on_off_calc_TP07, :on_off_calc_KS01,
                  :on_off_calc_KS02, :on_off_calc_KS03, :on_off_calc_KS04, :on_off_calc_PT01, :on_off_calc_PT02, :on_off_calc_PT03,
                  :on_off_calc_PT04, :rack_multiplicity, :otxod_pk, :otxod_sk, :otxod_pl, :otxod_trol, :job_natsen_diler_third, :job_natsen_diler_second,
                  :mat_shpingalet_naves, :wei_shpingalet_naves

  validates :job_stoyki_arx, :job_polki_arx, :job_usil_arx, :job_upakovka_arx, :job_ogranich,
            :job_okr_stoyki_arx, :job_okr_polki_arx, :job_stoyki_sklad, :job_traversi_sklad,
            :job_polki_sklad, :job_ukosi_sklad, :job_usil_styagnoy, :job_usil_g, :job_okr_usil_sklad,
            :job_okr_stoyki_sklad, :job_ork_polki_sklad, :job_okr_traversi_sklad, :job_upakovka_sklad,
            :job_stoyki_pallet, :job_traversi_pallet, :job_okr_travers_pallet, :job_ukosi_pallet,
            :job_svarka_ks_01, :job_svarka_ks_02, :job_svarka_ks_03, :job_svarka_ks_04,
            :job_svarka_pt_01, :job_svarka_pt_02, :job_svarka_pt_03, :job_svarka_pt_04,
            :job_svarka_tp_01, :job_svarka_tp_02, :job_svarka_tp_03, :job_svarka_tp_04,
            :job_svarka_tp_05, :job_svarka_tp_06, :job_svarka_tp_07, :job_rezka, :job_okr_telegek,
            :job_gibka_du_20_25,
            :job_rixtovka_ugolka, :job_upakovka_teleg, :job_rez_dsp_1mp, :job_natsenka,
            :job_dostavka_1kg, :job_kostven_arx, :job_kostven_sklad, :job_kostven_pallet,
            :job_kostven_telegi, :job_natsen_diler, :job_procent_udor_svarki_telegki,
            :mat_list_2_1_055, :mat_list_2_1_07, :mat_list_25_125_07, :mat_list_2_1_1, :mat_list_2_1_2,
            :mat_list_25_125_2, :mat_list_2_1_25, :mat_list_25_125_25, :mat_stoyki_arx, :mat_pyatki_arx,
            :mat_stoyki_sklad, :mat_traversa_sklad, :mat_pyatki_sklad, :mat_metizi_sklad, :mat_ukosi_sklad,
            :mat_zatsep_sklad, :mat_truba_25_25_12, :mat_truba_25_25_15, :mat_shina_30_4, :mat_skoba_styagnogo,
            :mat_stoyki_pallet, :mat_pyatki_pallet, :mat_metizi_pallet_ram, :mat_metizi_pallet_travers,
            :mat_zatsep_pallet, :mat_ukosi_pallet, :mat_truba_25_25_2, :mat_truba_du_20_25,
            :mat_plastini_teleg, :mat_metizi_teleg, :mat_ugolok_20_20_3, :mat_dsp_laminat, :mat_dsp_shlif,
            :mat_100x60x100x15,:mat_setka_50_50_3,
            :wei_list_2_1_055, :wei_list_2_1_07, :wei_list_25_125_07, :wei_list_2_1_1, :wei_list_2_1_2,
            :wei_list_25_125_2, :wei_list_2_1_25, :wei_list_25_125_25, :wei_stoyki_arx,
            :wei_pyatki_arx, :wei_stoyki_sklad, :wei_traversa_sklad, :wei_pyatki_sklad,
            :wei_metizi_sklad, :wei_ukosi_sklad, :wei_zatsep_sklad, :wei_truba_25_25_12,
            :wei_truba_25_25_15, :wei_truba_25_25_2,:wei_shina_30_4, :wei_skoba_styagnogo, :wei_stoyki_pallet,
            :wei_pyatki_pallet, :wei_metizi_pallet_ram, :wei_metizi_pallet_travers,
            :wei_zatsep_pallet, :wei_ukosi_pallet, :wei_truba_du_20_25, :wei_plastini_teleg,
            :wei_metizi_teleg, :wei_ugolok_20_20_3, :wei_dsp_laminat, :wei_dsp_shlif, :wei_100x60x100x15, :wei_setka_50_50_3,
            :rack_multiplicity, :otxod_pk, :otxod_sk, :otxod_pl, :otxod_trol, :job_natsen_diler_third, :job_natsen_diler_second,
            :mat_shpingalet_naves, :wei_shpingalet_naves,
            numericality: {greater_than: 0}, presence: true
end
